import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { JSDOM } from 'jsdom';
import { createApp } from '../server/app';
import { FIELD_LABELS, type TaskFields } from '../shared/types';

test('UI journey: clarify, confirm, publish, apply, select, confirm milestone', async () => {
 const dom = new JSDOM('<!doctype html><html><body></body></html>', {url:'http://localhost'});
 Object.assign(globalThis, {window:dom.window, document:dom.window.document, HTMLElement:dom.window.HTMLElement, Node:dom.window.Node, MutationObserver:dom.window.MutationObserver, IS_REACT_ACT_ENVIRONMENT:true});
 Object.defineProperty(globalThis, 'navigator', {value:dom.window.navigator,configurable:true});
 const {createElement} = await import('react');
 const {render, fireEvent, screen, within, waitFor, cleanup} = await import('@testing-library/react');
 const {default:App} = await import('../src/App');
 const dir=mkdtempSync(join(tmpdir(),'sana-ui-'));
 const server=createApp({dataFile:join(dir,'store.json')}).listen(0,'127.0.0.1');
 await new Promise<void>(resolve=>server.once('listening',resolve));
 const address=server.address(); assert.ok(address&&typeof address==='object');
 const originalFetch=globalThis.fetch;
 globalThis.fetch=((url: Parameters<typeof fetch>[0], options?: RequestInit) => originalFetch(typeof url==='string'&&url.startsWith('/')?`http://127.0.0.1:${address.port}${url}`:url, options)) as typeof fetch;
 try {
  render(createElement(App));
  await screen.findByRole('heading',{name:'Прогноз остатков магазина'});
  const scores=Array.from(document.querySelectorAll('.card-score b')).map(el=>Number(el.textContent));
  assert.deepEqual(scores,[...scores].sort((a,b)=>b-a));
  fireEvent.click(screen.getByRole('button',{name:/Создать задачу/}));
  fireEvent.change(screen.getByLabelText('Описание ситуации'),{target:{value:'В нашем магазине часто заканчиваются популярные товары.'}});
  fireEvent.click(screen.getByRole('button',{name:/Получить вопросы/}));
  await screen.findByRole('heading',{name:'Добавим конкретики'});
  assert.ok(document.querySelectorAll('.question-number').length>=3);
  fireEvent.click(screen.getByRole('button',{name:/Перейти к карточке/}));
  const values:TaskFields={title:'Тестовый прогноз спроса',context:'Магазин теряет продажи из-за дефицита.',need:'Планировать закупки по спросу.',users:'Менеджеры закупок.',data:'CSV продаж за шесть месяцев.',constraints:'Две недели без платных интеграций.',outcome:'Прототип прогноза.',success:'Снизить дефицит на 15%.',contact:'demo@example.org',interaction:'Созвон раз в неделю.'};
  for(const [field,label] of Object.entries(FIELD_LABELS)) fireEvent.change(screen.getByLabelText(label,{exact:true}),{target:{value:values[field as keyof TaskFields]}});
  const confirm=screen.getByRole('checkbox');
  fireEvent.click(confirm);
  assert.match(document.querySelector('.score-large')!.textContent!,/^100/);
  fireEvent.change(screen.getByLabelText('Пользователи',{exact:true}),{target:{value:'Менеджер закупок магазина.'}});
  assert.equal((confirm as HTMLInputElement).checked,false);
  assert.match(document.querySelector('.score-large')!.textContent!,/^0/);
  fireEvent.click(confirm);
  fireEvent.click(screen.getByRole('button',{name:/Опубликовать/}));
  await screen.findByRole('dialog',{name:values.title});
  fireEvent.click(screen.getByRole('button',{name:'Закрыть задачу'}));
  fireEvent.click(screen.getByRole('button',{name:'Команда'}));
  fireEvent.click(screen.getByRole('heading',{name:values.title}).closest('button')!);
  const dialog=within(screen.getByRole('dialog'));
  fireEvent.change(dialog.getByLabelText('Идея решения'),{target:{value:'Сделаем прогноз на основе продаж.'}});
  fireEvent.change(dialog.getByLabelText('План работы'),{target:{value:'Очистим данные, построим модель и проверим.'}});
  fireEvent.change(dialog.getByLabelText('Сроки'),{target:{value:'Две недели'}});
  fireEvent.change(dialog.getByLabelText('Ссылка на прототип'),{target:{value:'https://example.org/prototype'}});
  fireEvent.submit(dialog.getByRole('button',{name:/Отправить отклик/}).closest('form')!);
  await screen.findByRole('heading',{name:'Мои отклики'});
  fireEvent.click(screen.getByRole('button',{name:'Бизнес'}));
  const article=within(screen.getByText(values.title,{exact:true}).closest('article')!);
  fireEvent.click(article.getByRole('button',{name:'Выбрать команду'}));
  await article.findByText('Команда выбрана',{exact:true});
  await waitFor(()=>assert.equal((article.getByRole('button',{name:/Подтвердить результат/}) as HTMLButtonElement).disabled,false));
  fireEvent.click(article.getByRole('button',{name:/Подтвердить результат/}));
  await article.findByRole('button',{name:/Результат подтверждён/});
  const state=await (await fetch('/api/state')).json();
  assert.equal(state.teams.find((t:{id:string})=>t.id==='team-1').points,10);
  assert.equal(state.tasks.find((t:{title:string})=>t.title===values.title).published,true);
  await waitFor(()=>assert.equal((article.getByRole('button',{name:/Результат подтверждён/}) as HTMLButtonElement).disabled,true));
 } finally {
  cleanup();globalThis.fetch=originalFetch;
  await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));
  rmSync(dir,{recursive:true,force:true});dom.window.close();
 }
});
