import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { JSDOM } from 'jsdom';
import { createApp } from '../server/app';

test('cabinet UI: empty draft, short title, low-score publish, role registration, personal proposal and feedback',{timeout:15000},async()=>{
 const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'http://localhost'});
 Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,Node:dom.window.Node,MutationObserver:dom.window.MutationObserver,IS_REACT_ACT_ENVIRONMENT:true});
 Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
 const {createElement}=await import('react');
 const {render,fireEvent,screen,within,waitFor,cleanup}=await import('@testing-library/react');
 const {default:App}=await import('../src/App');
 const dir=mkdtempSync(join(tmpdir(),'sana-ui-'));
 const server=createApp({aiOptions:{apiKey:''},dataFile:join(dir,'store.json')}).listen(0,'127.0.0.1');
 await new Promise<void>(r=>server.once('listening',r));
 const address=server.address();assert.ok(address&&typeof address==='object');
 const originalFetch=globalThis.fetch;let cookie='';
 globalThis.fetch=(async(url,options)=>{
  const headers=new Headers(options?.headers);if(cookie)headers.set('Cookie',cookie);
  const result=await originalFetch(typeof url==='string'&&url.startsWith('/')?`http://127.0.0.1:${address.port}${url}`:url,{...options,headers});
  const setCookie=result.headers.getSetCookie();if(setCookie.length)cookie=setCookie[0].split(';')[0];
  return result;
 }) as typeof fetch;
 const click=async(name:string|RegExp)=>{await waitFor(()=>assert.equal(document.querySelector('header')?.hasAttribute('inert'),false));const button=await screen.findByRole('button',{name});await waitFor(()=>assert.equal((button as HTMLButtonElement).disabled,false));fireEvent.click(button);};
 const login=async(role:'business'|'team',name:string)=>{
  await click(role==='business'?'Бизнес':'Команда');
  fireEvent.change(screen.getByLabelText(role==='business'?'Название бизнеса':'Название команды'),{target:{value:name}});
  await click(/Открыть кабинет/);
  await waitFor(()=>assert.ok(!screen.queryByLabelText(role==='business'?'Название бизнеса':'Название команды')));
  await screen.findByRole('heading',{name:role==='business'?'Кабинет бизнеса':'Кабинет команды'});
 };
 try{
  render(createElement(App));
  await screen.findByRole('heading',{name:'Прогноз остатков магазина'});
  await login('business','Магазин для UI');
  await click('+ Новая задача');
  await click('Сохранить черновик');
  await screen.findByText(/Черновик сохранён в вашем кабинете/);
  const saved=(await(await fetch('/api/state')).json()).tasks.find((t:{title:string})=>t.title==='Без названия');
  assert.ok(saved);assert.equal(saved.published,false);
  await click(/Карточка/);
  fireEvent.change(screen.getByLabelText('Название задачи'),{target:{value:''}});
  await click(/Опубликовать задачу/);
  assert.ok(screen.getByRole('alert').textContent?.includes('Укажите название'));
  fireEvent.change(screen.getByLabelText('Название задачи'),{target:{value:'аб'}});
  fireEvent.change(screen.getByLabelText('Потребность'),{target:{value:'аю'}});
  assert.ok(document.querySelectorAll('.field-points').length===10);
  await click('Оценить качество с AI');
  await screen.findByText(/Качество оценено/);
  assert.match(document.querySelector('.score-large')!.textContent!,/^0/);
  await click(/Опубликовать задачу/);
  assert.match(screen.getByRole('alert').textContent!,/подтверждение/);
  fireEvent.click(screen.getByRole('checkbox'));
  await click(/Опубликовать задачу/);
  await screen.findByText(/Задача опубликована в общем каталоге/);
  fireEvent.change(screen.getByLabelText('Пользователи'),{target:{value:'аю'}});
  assert.equal((screen.getByRole('checkbox') as HTMLInputElement).checked,false);
  fireEvent.click(screen.getByRole('checkbox'));
  await click('Сохранить изменения');
  await screen.findByText(/Задача опубликована в общем каталоге/);
  await login('team','Моя новая команда');
  await click('Найти задачу ↗');
  fireEvent.click(screen.getByRole('heading',{name:'аб'}).closest('button')!);
  let dialog=within(screen.getByRole('dialog',{name:'аб'}));
  assert.equal(dialog.queryByRole('button',{name:/Редактировать/}),null);
  fireEvent.change(dialog.getByLabelText('Идея решения'),{target:{value:'Сделаем прогноз закупок'}});
  fireEvent.change(dialog.getByLabelText('План работы'),{target:{value:'Соберём данные и проверим модель'}});
  fireEvent.change(dialog.getByLabelText('Сроки'),{target:{value:'Неделя'}});
  fireEvent.submit(dialog.getByRole('button',{name:/Отправить отклик/}).closest('form')!);
  await screen.findByRole('heading',{name:'Мои отклики'});
  assert.equal(document.querySelectorAll('article').length,1);
  await login('business','Другой бизнес UI');
  await click(/Отклики/);assert.equal(document.querySelectorAll('article').length,0);
  await login('business','Магазин для UI');
  await click(/Отклики/);
  let article=within(document.querySelector('article')!);
  fireEvent.change(article.getByLabelText('Обратная связь команде'),{target:{value:'Предложите более конкретный план'}});
  await click('Отклонить');
  await article.findByText('Отклонён',{exact:true});
  await login('team','Моя новая команда');
  await click(/Отклики/);
  await screen.findByText('Предложите более конкретный план',{exact:true});
  assert.equal(screen.queryByRole('button',{name:'Отклонить'}),null);
  await login('business','Магазин для UI');await click(/Отклики/);
  await click('Выбрать команду');await screen.findByText('Команда выбрана',{exact:true});
  await click(/Подтвердить результат/);await screen.findByRole('button',{name:/Результат подтверждён/});
  const result=await(await fetch('/api/state')).json();
  assert.equal(result.teams.find((t:{name:string})=>t.name==='Моя новая команда').points,10);
 }finally{
  cleanup();globalThis.fetch=originalFetch;server.closeAllConnections();
  await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));
  rmSync(dir,{recursive:true,force:true});dom.window.close();
 }
});
