import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { JSDOM } from 'jsdom';
import { createApp } from '../server/app';
import { FIELD_MAX } from '../shared/scoring';
import { emptyFields, type Field, type TaskFields } from '../shared/types';

test('manual and explicit AI entry, recommendations, ranking, history and owned workflows',{timeout:30000},async()=>{
 const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'http://localhost/#/catalog'});
 Object.assign(globalThis,{window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,HTMLElement:dom.window.HTMLElement,Node:dom.window.Node,MutationObserver:dom.window.MutationObserver,IS_REACT_ACT_ENVIRONMENT:true});
 Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
 dom.window.scrollTo=()=>{};
 const {createElement}=await import('react');
 const {render,fireEvent,screen,within,waitFor,cleanup,act}=await import('@testing-library/react');
 const {default:App}=await import('../src/App');
 const extracted:TaskFields={...emptyFields(),title:'Прогноз для магазина',context:'Закупки магазина планируют вручную.',need:'Прогнозировать спрос на товары.',users:'Менеджеры закупок',data:'Обезличенный CSV продаж за 6 месяцев.',constraints:'Две недели',outcome:'Веб-прототип прогноза',success:'Сравнить ошибку прогноза',contact:'demo@example.org'};
 const points:Record<Field,number>={title:0,context:10,need:6,users:6,data:12,constraints:4,outcome:9,success:4,contact:5,interaction:0};
 let analysisCalls=0;let holdAnalysis=false;let releaseAnalysis:(()=>void)|undefined;
 const provider=(async(_url,init)=>{
  const body=JSON.parse(String(init?.body)),input=JSON.parse(body.input);
  if(body.text.format.name==='business_task_analysis')analysisCalls++;if(holdAnalysis){holdAnalysis=false;await new Promise<void>(resolve=>{releaseAnalysis=resolve;});}
  const merged={...extracted,...Object.fromEntries(Object.entries(input.provided??input.fields??{}).filter(([,v])=>v))} as TaskFields;
  const rows=(Object.keys(FIELD_MAX) as Field[]).map(field=>({field,value:merged[field],evidence:merged[field]&&input.description.includes(merged[field])?[merged[field]]:[],quality:merged[field]==='аю'?0:FIELD_MAX[field]?points[field]/FIELD_MAX[field]:1,reason:`Обоснование: ${field}`,improvement:field==='data'?'Уточните состав таблицы.':'',question:field==='data'?'Какие столбцы есть в вашей таблице продаж?':''}));
  const responseRows=body.text.format.name==='business_task_analysis'?rows:rows.map(({field,quality,reason,improvement})=>({field,quality,reason,improvement}));
  return new Response(JSON.stringify({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({fields:responseRows})}]}]}),{status:200});
 }) as typeof fetch;
 const dir=mkdtempSync(join(tmpdir(),'omnipotent-ui-'));
 const server=createApp({aiOptions:{apiKey:'test-secret',fetchImpl:provider},dataFile:join(dir,'store.json')}).listen(0,'127.0.0.1');
 await new Promise<void>(r=>server.once('listening',r));
 const address=server.address();assert.ok(address&&typeof address==='object');
 const originalFetch=globalThis.fetch;let cookie='';let holdSave=false;let releaseSave:(()=>void)|undefined;
 globalThis.fetch=(async(url,options)=>{
  const headers=new Headers(options?.headers);if(cookie)headers.set('Cookie',cookie);
  const result=await originalFetch(typeof url==='string'&&url.startsWith('/')?`http://127.0.0.1:${address.port}${url}`:url,{...options,headers});
  const setCookie=result.headers.getSetCookie();if(setCookie.length)cookie=setCookie[0].split(';')[0];
  if(holdSave&&options?.method==='POST'&&url==='/api/tasks'){holdSave=false;await new Promise<void>(resolve=>{releaseSave=resolve;});}
  return result;
 }) as typeof fetch;
 const click=async(name:string|RegExp)=>{const button=await screen.findByRole('button',{name});await waitFor(()=>assert.ok(!(button as HTMLButtonElement).disabled));fireEvent.click(button);};
 const go=async(path:string)=>{await act(async()=>{window.location.hash=path;await new Promise(r=>setTimeout(r,10));});};
 const login=async(role:'business'|'team',name:string)=>{
  await go(`/login/${role}`);
  fireEvent.change(await screen.findByLabelText(role==='business'?'Название бизнеса':'Название команды'),{target:{value:name}});
  await click(/Открыть кабинет/);
  await waitFor(()=>assert.ok(!screen.queryByLabelText(role==='business'?'Название бизнеса':'Название команды')));
 };
 try{
  render(createElement(App));
  await screen.findByRole('heading',{name:'Прогноз остатков магазина'});
  assert.ok(screen.getByRole('link',{name:/Мой кабинет/}));
  await login('business','Магазин для UI');
  await click('+ Новая задача');
  holdSave=true;await click('Сохранить черновик');
  await waitFor(()=>assert.ok(releaseSave));
  fireEvent.change(screen.getByLabelText('Название задачи'),{target:{value:'Новая правка во время сохранения'}});
  await act(async()=>{releaseSave!();});
  await screen.findByText(/Предыдущая версия сохранена/);
  assert.equal((screen.getByLabelText('Название задачи') as HTMLInputElement).value,'Новая правка во время сохранения');
  const saved=(await(await fetch('/api/state')).json()).tasks.find((t:{title:string})=>t.title==='Без названия');assert.ok(saved);assert.equal(saved.published,false);
  await click('Сохранить черновик');await screen.findByText(/Черновик сохранён/);
  const latest=(await(await fetch('/api/state')).json()).tasks.filter((t:{businessId:string})=>t.businessId===saved.businessId);assert.equal(latest.length,1,'An in-flight create must not lead to a duplicate task on next save');assert.equal(latest[0].title,'Новая правка во время сохранения');
  fireEvent.change(screen.getByLabelText('Название задачи'),{target:{value:''}});
  await click(/Опубликовать задачу/);assert.ok(screen.getAllByRole('alert').some(el=>el.textContent?.includes('название')));
  fireEvent.change(screen.getByLabelText('Название задачи'),{target:{value:'Прогноз для магазина'}});
  fireEvent.change(screen.getByLabelText('Описание ситуации'),{target:{value:Object.values(extracted).filter(Boolean).join('\n')}});
  await act(async()=>{await new Promise(r=>setTimeout(r,1600));});assert.equal(analysisCalls,0);assert.equal((screen.getByLabelText('Данные и материалы') as HTMLTextAreaElement).value,'');
  await click('Распределить описание с AI');
  await waitFor(()=>assert.equal((screen.getByLabelText('Данные и материалы') as HTMLTextAreaElement).value,extracted.data),{timeout:5000});
  assert.ok(screen.getByLabelText('56 из 100 баллов'));
  assert.ok(screen.getByText('Какие столбцы есть в вашей таблице продаж?',{exact:false}));
  assert.ok(!screen.queryByRole('button',{name:/Получить вопросы|Оценить качество/}));
  const n=analysisCalls;await act(async()=>{await new Promise(r=>setTimeout(r,1600));});assert.equal(analysisCalls,n,'AI field application must not cause an analysis loop');
  holdAnalysis=true;
  fireEvent.change(screen.getByLabelText('Данные и материалы'),{target:{value:'CSV с уточнёнными столбцами товаров'}});
  await waitFor(()=>assert.ok(releaseAnalysis),{timeout:5000});
  fireEvent.change(screen.getByLabelText('Потребность'),{target:{value:'аю'}});
  await act(async()=>{releaseAnalysis!();});
  await waitFor(()=>assert.ok(screen.queryByLabelText('50 из 100 баллов')),{timeout:5000});
  assert.equal((screen.getByLabelText('Потребность') as HTMLTextAreaElement).value,'аю');assert.equal((screen.getByLabelText('Данные и материалы') as HTMLTextAreaElement).value,'CSV с уточнёнными столбцами товаров');
  fireEvent.click(screen.getByRole('checkbox'));
  await click(/Опубликовать задачу/);
  await screen.findByText(/сохранена и опубликована/);
  await go(`/tasks/${saved.id}`);
  await screen.findByRole('heading',{name:'Прогноз для магазина'});
  assert.ok(screen.getByText('#3 из 6 в каталоге'));assert.ok(screen.getByRole('heading',{name:'Как улучшить задачу'}));
  await go('/cabinet');assert.ok(screen.getByText('Улучшить задачу →'));
  await go(`/tasks/${saved.id}`);
  await click('☆ В избранное');await click('Отметить как решённую');
  await screen.findByRole('button',{name:'Вернуть в открытые'});
  await go('/favorites');await screen.findByRole('heading',{name:'Прогноз для магазина'});
  fireEvent.change(screen.getByLabelText('Статус задачи'),{target:{value:'Открыто'}});
  assert.ok(!screen.queryByRole('heading',{name:'Прогноз для магазина'}));
  fireEvent.change(screen.getByLabelText('Статус задачи'),{target:{value:'Решено'}});
  assert.ok(screen.getByRole('heading',{name:'Прогноз для магазина'}));
  fireEvent.change(screen.getByLabelText('Уровень готовности'),{target:{value:'Рабочая'}});
  assert.ok(screen.getByRole('heading',{name:'Прогноз для магазина'}));
  fireEvent.change(screen.getByLabelText('Уровень готовности'),{target:{value:'Готовая'}});
  assert.ok(!screen.queryByRole('heading',{name:'Прогноз для магазина'}));
  await go('/cabinet');await act(async()=>{window.history.back();await new Promise(r=>setTimeout(r,25));});
  await screen.findByRole('heading',{name:/Избранные задачи/});
  await go(`/tasks/${saved.id}`);await click('Вернуть в открытые');await screen.findByRole('button',{name:'Отметить как решённую'});
  await login('team','Команда для UI');await go('/tasks/task-1');
  await screen.findByRole('heading',{name:'Орбита'}); // Another team's published solution is public.
  assert.ok(!screen.queryByRole('button',{name:'Удалить мой отклик'}));
  await go(`/tasks/${saved.id}`);
  fireEvent.change(screen.getByLabelText('Идея решения'),{target:{value:'Сделаем прогноз спроса'}});
  fireEvent.change(screen.getByLabelText('План работы'),{target:{value:'Проверим CSV и сравним модели'}});
  fireEvent.change(screen.getByLabelText('Сроки'),{target:{value:'Неделя'}});
  await click(/Опубликовать решение/);await screen.findByText(/Ваше решение опубликовано/);
  await login('business','Магазин для UI');await go('/proposals');
  fireEvent.change(screen.getByLabelText('Обратная связь команде'),{target:{value:'Уточните план проверки'}});
  await click('Отклонить');await screen.findByText('Отклонён',{exact:true});
  await login('team','Команда для UI');await screen.findByText('Уточните план проверки',{exact:true});
  await click('Удалить мой отклик');await click('Да, удалить отклик');
  await waitFor(()=>assert.ok(!screen.queryByText('Сделаем прогноз спроса',{exact:true})));
  await login('business','Магазин для UI');await go(`/tasks/${saved.id}`);
  await click('Удалить задачу');await click('Да, удалить задачу');
  await screen.findByText('Задача удалена.',{exact:true});
  const after=await(await fetch('/api/state')).json();assert.ok(!after.tasks.some((t:{id:string})=>t.id===saved.id));assert.ok(!after.favoriteTaskIds.includes(saved.id));
 }finally{
  cleanup();globalThis.fetch=originalFetch;server.closeAllConnections();
  await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));
  rmSync(dir,{recursive:true,force:true});dom.window.close();
 }
});
