import { emptyFields, type AppState, type Task } from '../shared/types.js';
import { withSeedAssessment } from './seed-assessments.js';
export function seedState():AppState {
 const names=['Прогноз остатков магазина','Запись клиентов в мастерскую','Учёт обращений в кофейне','Каталог местного музея','Анализ заявок учебного центра'];
 const industries=['Розничная торговля','Услуги','Общепит','Культура','Образование'];
 const descriptions=['В магазине заканчиваются популярные товары. Хотим понять, что заказывать.','Клиенты записываются по телефону, записи иногда теряются.','Отзывы посетителей остаются в разных чатах. Нужен единый учёт.','Нужно сделать коллекцию музея доступнее посетителям.','Хотим понять, почему часть заявок на курсы не доходит до оплаты.'];
 const tasks:Task[]=names.map((title,i)=>({...emptyFields(),title,context:descriptions[i],need:i>0?'Сократить ручную работу и потери информации.':'',users:i>1?'Сотрудники организации и руководитель.':'',data:i>1?'Обезличенная таблица за три месяца; передадим выбранной команде.':'',constraints:i>2?'Демонстрация через две недели, без платных интеграций.':'',outcome:i>2?'Рабочий прототип и краткая инструкция.':'',success:i>3?'Пять типовых сценариев проходят без потери данных.':'',contact:i>2?`demo${i}@business.example (демо-контакт)`:'',interaction:i>3?'Созвон раз в неделю и обратная связь в чате.':'',id:`task-${i+1}`,businessId:`business-${i+1}`,industry:industries[i],description:descriptions[i],confirmed:true,published:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})).map(withSeedAssessment);
 const teams=['Орбита','Алгоритм','Пиксель','Импульс','Маяк'].map((name,i)=>({id:`team-${i+1}`,name,interests:[industries[i]],skills:['Прототипирование',i%2?'UX':'Аналитика'],technologies:['TypeScript','React'],points:0}));
 return {businesses:['Магазин У дома','Мастерская','Кофейня','Музей','Учебный центр'].map((name,i)=>({id:`business-${i+1}`,name})),tasks,teams,drafts:descriptions.map((description,i)=>({description,industry:industries[i]})),proposals:tasks.map((task,i)=>({id:`proposal-${i+1}`,taskId:task.id,teamId:teams[i].id,idea:'Соберём простой прототип для проверки гипотезы.',plan:'Уточним процесс, подготовим интерфейс, проверим на примерах.',timeline:'Две недели после согласования задачи.',prototypeUrl:`https://example.org/demo-prototype-${i+1}`,status:'pending',milestoneConfirmed:false,createdAt:new Date().toISOString()}))};
}
