import { useEffect, useState } from 'react';
import { emptyFields, FIELD_LABELS, type AppState, type Clarification, type Field, type Identity, type QualityAssessment, type Task, type TaskFields } from '../shared/types';
import { calculateScore, FIELD_MAX } from '../shared/scoring';

const fields = Object.keys(FIELD_LABELS) as Field[];
const initial: AppState = { businesses: [], tasks: [], teams: [], proposals: [], drafts: [] };
const hints: TaskFields = { title: 'Короткое понятное название', context: 'Что происходит сейчас? Например: магазин с 200 товарами ведёт остатки в Excel.', need: 'Что мешает бизнесу? Опишите конкретную проблему и её последствия.', users: 'Кто будет пользоваться решением? Укажите роль и сценарий.', data: 'Какие данные есть: формат, объём, период, пример и условия доступа?', constraints: 'Срок, бюджет, технологии, ограничения и что не входит в задачу.', outcome: 'Что команда должна передать: прототип, отчёт, код или другой результат?', success: 'Как измерить успех? Метрика, целевое значение и способ проверки.', contact: 'Ответственный: имя и рабочая почта или другой способ связи.', interaction: 'Когда и как общаться: канал, частота встреч, доступность эксперта.' };
async function api<T>(path: string, method = 'GET', body?: unknown): Promise<T> {
  const response = await fetch(path, { method, headers: { 'Content-Type': 'application/json' }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || 'Не удалось выполнить запрос. Попробуйте ещё раз.');
  return data as T;
}
function ScoreView({ values, confirmed, assessment }: { values: TaskFields; confirmed: boolean; assessment?: QualityAssessment }) {
  const score = calculateScore(values, Boolean(assessment) || confirmed, assessment);
  return <aside className="score-panel"><span className="eyebrow">{!confirmed ? 'ПРЕДВАРИТЕЛЬНАЯ ОЦЕНКА' : 'ГОТОВНОСТЬ ЗАДАЧИ'}</span><div className="score-large">{score.total}<span>/ 100</span></div><span className="status">{score.level}</span><p className="muted">Баллы отражают полноту и качество сведений, а не длину текста.</p>{!confirmed && <p className="notice">Это предпросмотр. Сохранённый рейтинг фиксируется только после вашего подтверждения.</p>}<div className="score-lines">{score.items.map(item => <div key={item.key}><div className="split"><span>{item.label}</span><b>{item.points}/{item.max}</b></div><div className="meter"><i style={{ width: `${item.points / item.max * 100}%` }} /></div>{item.reason && <p className="small muted">{item.reason}</p>}</div>)}</div>{assessment && <p className="notice">{assessment.mode === 'openai' ? 'Оценка AI' : 'Резервная оценка по правилам'}: {assessment.notice}</p>}<p className="small muted">Низкий рейтинг не блокирует публикацию и отклики.</p></aside>;
}
export default function App() {
  const [state, setState] = useState<AppState>(initial);
  const [identity, setIdentity] = useState<Identity | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');
  const [formError, setFormError] = useState('');
  const [saveMessage, setSaveMessage] = useState('');
  const [tab, setTab] = useState<'catalog' | 'cabinet' | 'builder' | 'proposals'>('catalog');
  const [loginRole, setLoginRole] = useState<'business' | 'team' | null>(null);
  const [loginName, setLoginName] = useState('');
  const [query, setQuery] = useState('');
  const [industryFilter, setIndustryFilter] = useState('Все отрасли');
  const [level, setLevel] = useState('Все уровни');
  const [selected, setSelected] = useState<Task | null>(null);
  const [values, setValues] = useState<TaskFields>(emptyFields());
  const [description, setDescription] = useState('');
  const [industry, setIndustry] = useState('Торговля');
  const [confirmed, setConfirmed] = useState(false);
  const [assessment, setAssessment] = useState<QualityAssessment>();
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editingPublished, setEditingPublished] = useState(false);
  const [clarification, setClarification] = useState<Clarification | null>(null);
  const [stage, setStage] = useState(1);
  const [proposal, setProposal] = useState({ idea: '', plan: '', timeline: '', prototypeUrl: '' });
  const [feedback, setFeedback] = useState<Record<string, string>>({});
  const [aiStatus, setAiStatus] = useState('');
  const reload = async () => setState(await api<AppState>('/api/state'));
  useEffect(() => { Promise.all([reload(), api<Identity | null>('/api/session').then(session => { setIdentity(session); if (session) setTab('cabinet'); }), api<{ configured: boolean; model: string | null }>('/api/ai/status').then(status => setAiStatus(status.configured ? `AI настроен: ${status.model}. При оценке описание и поля отправляются в OpenAI.` : 'Ключ AI не настроен: доступна консервативная оценка по правилам')).catch(() => setAiStatus('Статус AI недоступен'))]).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!selected) return; const before = document.activeElement as HTMLElement | null; const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') setSelected(null); if (e.key === 'Tab') { const controls = Array.from(document.querySelectorAll<HTMLElement>('.modal button:not(:disabled), .modal a, .modal input, .modal select, .modal textarea')); const first = controls[0], last = controls[controls.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } } }; document.addEventListener('keydown', handler); const old = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.removeEventListener('keydown', handler); document.body.style.overflow = old; before?.focus(); }; }, [selected]);
  const perform = async (fn: () => Promise<void>) => { setBusy(true); setError(''); setMessage(''); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : 'Произошла ошибка'); } finally { setBusy(false); } };
  const invalidate = () => { setConfirmed(false); setAssessment(undefined); setSaveMessage(''); setFormError(''); };
  const update = (field: Field, value: string) => { setValues(current => ({ ...current, [field]: value })); invalidate(); };
  const openLogin = (role: 'business' | 'team') => { setLoginRole(role); setLoginName(window.localStorage.getItem(`sana-name-${role}`) || ''); setSelected(null); setError(''); setTab('cabinet'); };
  const signIn = () => perform(async () => { const name = loginName.trim(); if (!name) throw new Error('Введите название бизнеса или команды.'); const session = await api<Identity>('/api/session', 'POST', { role: loginRole, name }); setIdentity(session); window.localStorage.setItem(`sana-name-${session.role}`, session.name); setLoginRole(null); await reload(); setTab('cabinet'); setMessage(`Добро пожаловать, ${session.name}!`); });
  const newTask = () => { if (identity?.role !== 'business') { openLogin('business'); return; } setValues(emptyFields()); setDescription(''); setIndustry('Торговля'); setConfirmed(false); setAssessment(undefined); setEditingId(null); setEditingPublished(false); setClarification(null); setStage(1); setSelected(null); setTab('builder'); setMessage(''); setError(''); setFormError(''); setSaveMessage(''); };
  const editTask = (t: Task) => { setValues(Object.fromEntries(fields.map(f => [f, t[f]])) as TaskFields); setDescription(t.description); setIndustry(t.industry); setConfirmed(t.confirmed); setAssessment(t.assessment); setEditingId(t.id); setEditingPublished(t.published); setClarification(null); setStage(3); setSelected(null); setTab('builder'); setSaveMessage(''); setFormError(''); };
  const clarify = () => { if (!description.trim()) { setFormError('Опишите ситуацию хотя бы одним предложением или перейдите к карточке.'); document.getElementById('description')?.focus(); return; } void perform(async () => { const result = await api<Clarification>('/api/clarify', 'POST', { description, industry, fields: values }); setClarification(result); setValues(result.fields); invalidate(); setStage(2); }); };
  const assess = () => perform(async () => { const result = await api<QualityAssessment>('/api/assess', 'POST', { fields: values, description, industry }); setAssessment(result); setSaveMessage('Качество оценено. Посмотрите баллы и рекомендации у каждого поля.'); });
  const save = (published: boolean) => {
    setFormError(''); setSaveMessage('');
    if (published && !values.title.trim()) { setStage(3); setFormError('Укажите название задачи. Достаточно любого непустого названия.'); setTimeout(() => document.getElementById('field-title')?.focus(), 0); return; }
    if (published && !confirmed) { setStage(3); setFormError('Проверьте карточку и отметьте подтверждение перед публикацией.'); setTimeout(() => document.getElementById('confirm-task')?.focus(), 0); return; }
    void perform(async () => { const task = await api<Task>(editingId ? `/api/tasks/${editingId}` : '/api/tasks', editingId ? 'PUT' : 'POST', { fields: values, description, industry, confirmed, published }); setEditingId(task.id); setEditingPublished(task.published); setAssessment(task.assessment); setValues(Object.fromEntries(fields.map(f => [f, task[f]])) as TaskFields); await reload(); setSaveMessage(published ? '✓ Изменения сохранены. Задача опубликована в общем каталоге.' : '✓ Черновик сохранён в вашем кабинете.'); });
  };
  const sendProposal = () => perform(async () => { await api('/api/proposals', 'POST', { taskId: selected!.id, ...proposal }); await reload(); setMessage('Отклик отправлен! Он появился в кабинете команды.'); setSelected(null); setTab('proposals'); });
  const published = state.tasks.filter(t => t.published);
  const ownTasks = state.tasks.filter(t => t.businessId === identity?.profileId);
  const visible = published.filter(t => (industryFilter === 'Все отрасли' || t.industry === industryFilter) && (level === 'Все уровни' || calculateScore(t, t.confirmed, t.assessment).level === level) && `${t.title} ${t.need} ${t.industry}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => calculateScore(b, b.confirmed, b.assessment).total - calculateScore(a, a.confirmed, a.assessment).total);
  const ownTeam = state.teams.find(t => t.id === identity?.profileId);
  const renderTask = (task: Task, index: number) => { const score = calculateScore(task, task.confirmed, task.assessment); return <button className="task-card" key={task.id} onClick={() => { setSelected(task); setError(''); setProposal({ idea: '', plan: '', timeline: '', prototypeUrl: '' }); }}><div className="split"><span className={`industry-icon tone-${index % 4}`}>{task.industry.slice(0, 1)}</span><span className="tag">{task.industry}</span></div><h3>{task.title}</h3><span className="business-name">{state.businesses.find(b => b.id === task.businessId)?.name || 'Бизнес'}</span><p>{task.need || task.description || 'Описание ещё готовится'}</p><div className="card-score"><span className="status">{task.published ? score.level : 'Не опубликовано'}</span><span><b>{score.total}</b> / 100</span></div><div className="meter"><i style={{ width: `${score.total}%` }} /></div><div className="card-footer"><span>{task.confirmed ? 'Подтверждено бизнесом' : 'Ожидает подтверждения'}</span><b>Подробнее ↗</b></div></button>; };
  const fieldQuality = (field: Field) => assessment?.fields.find(item => item.field === field);
  const fieldInput = (field: Field, question?: string) => { const quality = fieldQuality(field); const max = FIELD_MAX[field]; return <label className="quality-field" key={field} htmlFor={`field-${field}`}><span className="field-heading"><span>{question || FIELD_LABELS[field]}</span><span className="field-points">{max ? quality ? `${quality.points}/${max} · ещё +${max - quality.points}` : `до +${max}` : 'Без баллов'}</span></span>{field === 'title' ? <input disabled={busy} id={`field-${field}`} aria-label={question || FIELD_LABELS[field]} maxLength={160} value={values[field]} placeholder={hints[field]} onChange={e => update(field, e.target.value)} /> : <textarea disabled={busy} id={`field-${field}`} aria-label={question || FIELD_LABELS[field]} maxLength={5000} rows={3} value={values[field]} placeholder={hints[field]} onChange={e => update(field, e.target.value)} />}<span className="field-hint">{hints[field]}</span>{quality && <span className="quality-reason"><b>{quality.reason}</b>{quality.improvement && <span>Как улучшить: {quality.improvement}</span>}</span>}</label>; };
  return <div className="app"><header className="topbar" inert={busy}><a className="brand" href="#" onClick={e => { e.preventDefault(); setTab('catalog'); setLoginRole(null); }}><span className="brand-mark">s</span>sana<span className="brand-dot">.</span></a><span className="brand-caption">Реальные задачи.<br />Общий результат.</span><nav aria-label="Основная навигация"><button className={tab === 'catalog' && !loginRole ? 'active' : ''} onClick={() => { setTab('catalog'); setLoginRole(null); }}>Каталог задач</button>{identity && <><button className={(tab === 'cabinet' || tab === 'builder') && !loginRole ? 'active' : ''} onClick={() => { setTab('cabinet'); setLoginRole(null); }}>{identity.role === 'business' ? 'Мои задачи' : 'Мои решения'}</button><button className={tab === 'proposals' ? 'active' : ''} onClick={() => { setTab('proposals'); setLoginRole(null); }}>Отклики <span className="nav-count">{state.proposals.length}</span></button></>}</nav><div className="mode-switch" aria-label="Вход в кабинет"><button aria-pressed={loginRole === 'business' || (!loginRole && identity?.role === 'business')} onClick={() => openLogin('business')}>Бизнес</button><button aria-pressed={loginRole === 'team' || (!loginRole && identity?.role === 'team')} onClick={() => openLogin('team')}>Команда</button></div>{identity && <button className="logout" title="Выйти из кабинета" onClick={() => perform(async () => { await api('/api/session', 'DELETE'); setIdentity(null); setLoginRole(null); setTab('catalog'); await reload(); })}>Выйти</button>}</header><main><div className="demo-bar"><span><i /> ПРОТОТИП HACKALEM</span><span>{identity ? `${identity.role === 'business' ? 'Бизнес' : 'Команда'} · ${identity.name}` : 'Реальные задачи для студенческих команд'}</span></div>{error && <div role="alert" className="alert error">{error}<button onClick={() => setError('')} aria-label="Закрыть ошибку">×</button></div>}{message && <div role="status" className="alert success">{message}<button onClick={() => setMessage('')} aria-label="Закрыть уведомление">×</button></div>}
    {loginRole ? <section className="login-layout"><div><span className="eyebrow">{loginRole === 'business' ? 'ДАЙТЕ ИДЕЯМ ПРАКТИКУ' : 'ПРИМЕНИТЕ СВОИ НАВЫКИ'}</span><h1>{loginRole === 'business' ? 'Кабинет бизнеса' : 'Кабинет команды'}</h1><p className="muted">{loginRole === 'business' ? 'Создавайте задачи, улучшайте их качество и выбирайте команды из входящих откликов.' : 'Находите задачи, предлагайте решения и следите за ответами бизнеса.'}</p></div><form className="panel" onSubmit={e => { e.preventDefault(); void signIn(); }}><h2>{loginRole === 'business' ? 'Ваш бизнес' : 'Ваша команда'}</h2><label>{loginRole === 'business' ? 'Название бизнеса' : 'Название команды'}<input disabled={busy} autoFocus maxLength={100} value={loginName} onChange={e => setLoginName(e.target.value)} placeholder={loginRole === 'business' ? 'Например, Магазин Алем' : 'Например, Omnipotent'} /></label><button className="primary" disabled={busy}>{busy ? 'Открываем…' : 'Открыть кабинет →'}</button><div className="examples"><h4>Открыть существующий кабинет</h4>{(loginRole === 'business' ? state.businesses : state.teams).map(profile => <button type="button" key={profile.id} onClick={() => setLoginName(profile.name)}>{profile.name} ↗</button>)}</div><p className="small muted login-note">Вход по имени для прототипа. То же имя открывает тот же кабинет, пароль не требуется.</p></form></section> : <>
    {tab === 'catalog' && <><section className="hero"><div><span className="eyebrow">ОТ ИДЕИ К ПЕРВОМУ РЕЗУЛЬТАТУ</span><h1>Большие решения<br />начинаются с <em>задачи.</em></h1><p>Бизнес делится вызовами. Команды предлагают решения.<br />Вместе превращаем практику в реальную пользу.</p><button className="primary" onClick={identity?.role === 'team' ? () => document.getElementById('catalog')?.scrollIntoView({ behavior: 'smooth' }) : newTask}>{identity?.role === 'team' ? 'Найти задачу' : 'Создать задачу'} <span>↗</span></button></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><span className="art-star">✳</span><div className="art-card"><span className="tiny-label">ИЗ ИДЕИ — В ДЕЛО</span><div className="art-check">✓</div><b>Есть задача.<br />Найдётся команда.</b><div className="art-progress"><i /></div><span className="art-bottom">Понятная цель → Общий результат</span></div><span className="art-badge">+ опыт<br /><b>+ польза</b></span></div></section><section className="stats"><div><strong>{published.length.toString().padStart(2, '0')}</strong><span>задач для реальной практики</span></div><div><strong>{state.teams.length.toString().padStart(2, '0')}</strong><span>команд с разными навыками</span></div><div><strong>{state.businesses.length.toString().padStart(2, '0')}</strong><span>бизнесов с реальными задачами</span></div><div className="stat-note"><span className="mini-spark">✳</span><span>Ваш опыт нужен<br /><b>реальному бизнесу</b></span></div></section><section id="catalog"><div className="section-heading"><div><span className="eyebrow">НАЙДИТЕ СВОЙ ВЫЗОВ</span><h2>Каталог задач <span>{published.length}</span></h2></div><p>Откликнуться можно при любом рейтинге</p></div><div className="filters"><label className="search"><span aria-hidden="true">⌕</span><input disabled={busy} aria-label="Поиск задач" placeholder="Название, проблема или отрасль" value={query} onChange={e => setQuery(e.target.value)} /></label><select disabled={busy} aria-label="Отрасль" value={industryFilter} onChange={e => setIndustryFilter(e.target.value)}>{['Все отрасли', ...new Set(published.map(t => t.industry))].map(v => <option key={v}>{v}</option>)}</select><select disabled={busy} aria-label="Уровень готовности" value={level} onChange={e => setLevel(e.target.value)}>{['Все уровни', 'Черновик', 'Рабочая', 'Готовая', 'Приоритетная'].map(v => <option key={v}>{v}</option>)}</select></div>{loading ? <p role="status" className="empty">Загружаем задачи…</p> : <div className="task-grid">{visible.map(renderTask)}{!visible.length && <div className="empty">Задач пока нет. Измените фильтры или создайте первую.</div>}</div>}</section></>}
    {tab === 'cabinet' && identity && <><div className="page-title"><div><span className="eyebrow">{identity.name}</span><h1>{identity.role === 'business' ? 'Кабинет бизнеса' : 'Кабинет команды'}</h1><p>{identity.role === 'business' ? 'Ваши задачи, черновики и будущие совместные проекты.' : 'Ваши решения и ответы бизнеса в одном месте.'}</p></div><button className="primary" onClick={identity.role === 'business' ? newTask : () => setTab('catalog')}>{identity.role === 'business' ? '+ Новая задача' : 'Найти задачу ↗'}</button></div><div className="cabinet-summary"><span>{identity.role === 'business' ? `${ownTasks.length} задач` : `${ownTeam?.points || 0} баллов за результаты`}</span><button onClick={() => setTab('proposals')}>{state.proposals.length} {identity.role === 'business' ? 'входящих откликов' : 'моих откликов'} →</button></div>{identity.role === 'business' ? <div className="task-grid">{ownTasks.map(renderTask)}{!ownTasks.length && <div className="panel empty">Здесь появятся ваши задачи. Начните с описания бизнес-проблемы.</div>}</div> : <div className="panel"><h2>От идеи — к первому решению</h2><p className="muted">Выберите задачу в общем каталоге и отправьте идею. Ссылку на прототип можно добавить, когда он будет готов.</p><button className="secondary" onClick={() => setTab('proposals')}>Открыть мои отклики →</button></div>}</>}
    {tab === 'builder' && identity?.role === 'business' && <><div className="page-title"><div><span className="eyebrow">{identity.name} · СФОРМУЛИРУЕМ ВМЕСТЕ</span><h1>От проблемы к задаче</h1><p>{aiStatus}</p></div><button disabled={busy} className="secondary" onClick={() => setTab('cabinet')}>← В кабинет</button></div><div className="builder-layout"><section><div className="steps" inert={busy}>{['Описание', 'Уточнение', 'Карточка'].map((name, i) => <button key={name} className={stage === i + 1 ? 'current' : ''} onClick={() => setStage(i + 1)}><span>{i + 1}</span>{name}</button>)}</div><div className="panel">{stage === 1 && <><span className="eyebrow">ШАГ 01</span><h2>Что хотите улучшить?</h2><label>Отрасль<select disabled={busy} value={industry} onChange={e => { setIndustry(e.target.value); invalidate(); }}>{[...new Set(['Торговля', 'Образование', 'Услуги', 'Производство', 'Экология', 'Другое', industry, ...state.drafts.map(d => d.industry)])].map(v => <option key={v}>{v}</option>)}</select></label><label htmlFor="description">Описание ситуации<textarea disabled={busy} id="description" maxLength={5000} rows={6} value={description} placeholder="У нас небольшой магазин. Популярные товары заканчиваются неожиданно…" onChange={e => { setDescription(e.target.value); invalidate(); }} /></label><div className="actions"><button className="primary" disabled={busy} onClick={clarify}>{busy ? 'Готовим вопросы…' : 'Получить вопросы →'}</button><button disabled={busy} className="text-button" onClick={() => setStage(3)}>Заполнить вручную</button></div></>}{stage === 2 && <><span className="eyebrow">ШАГ 02</span><h2>Добавим конкретики</h2>{clarification ? <><p className="notice">{clarification.notice}</p>{clarification.questions.map(q => fieldInput(q.field, q.question))}</> : <p className="muted">Получите вопросы на первом шаге или сразу заполните карточку. Ваши ответы сохраняются при переходах.</p>}<button disabled={busy} className="primary" onClick={() => setStage(3)}>Перейти к карточке →</button></>}{stage === 3 && <><span className="eyebrow">ШАГ 03</span><h2>Карточка вашей задачи</h2><p className="muted">У каждого поля указан его точный вклад в 100 баллов. AI проверяет конкретность и полезность ответа.</p>{fields.map(f => fieldInput(f))}<button className="secondary" disabled={busy} onClick={() => void assess()}>{busy ? 'Оцениваем…' : 'Оценить качество с AI'}</button><label className="confirmation" htmlFor="confirm-task"><input disabled={busy} id="confirm-task" type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} /><span>Я проверил(а) и подтверждаю сведения. После редактирования потребуется новое подтверждение.</span></label></>}
    {formError && <p className="inline-form-error" role="alert">{formError}</p>}{saveMessage && <p className="inline-form-success" role="status">{saveMessage}</p>}{error && <p className="inline-form-error" role="alert">{error}</p>}<div className="actions save-actions"><button className="primary" disabled={busy} onClick={() => save(editingPublished || stage === 3)}>{busy ? (confirmed ? 'Проверяем качество и сохраняем…' : 'Сохраняем…') : editingPublished ? 'Сохранить изменения' : stage === 3 ? 'Опубликовать задачу ↗' : 'Сохранить черновик'}</button>{stage === 3 && !editingPublished && <button className="secondary" disabled={busy} onClick={() => save(false)}>Сохранить черновик</button>}{editingPublished && <button className="text-button" disabled={busy} onClick={() => save(false)}>Снять с публикации</button>}</div><p className="small muted">Черновик можно сохранить с пустыми полями. Для публикации нужны только название и подтверждение — любой рейтинг допустим.</p></div></section><ScoreView values={values} confirmed={confirmed} assessment={assessment} /></div></>}
    {tab === 'proposals' && identity && <><div className="page-title"><div><span className="eyebrow">{identity.name}</span><h1>{identity.role === 'business' ? 'Входящие отклики' : 'Мои отклики'}</h1><p>{identity.role === 'business' ? 'Выберите одну, несколько команд или ни одной. Объясните решение в обратной связи.' : 'Здесь — ваши предложения, решения бизнеса и обратная связь.'}</p></div></div><div className="proposal-list">{state.proposals.map(p => { const task = state.tasks.find(t => t.id === p.taskId), team = state.teams.find(t => t.id === p.teamId); return <article className="panel proposal-card" key={p.id}><div className="split"><div><span className="eyebrow">{task?.title || 'Задача бизнеса'}</span><h3>{team?.name || identity.name}</h3></div><span className={`status ${p.status === 'rejected' ? 'neutral' : ''}`}>{p.status === 'selected' ? 'Команда выбрана' : p.status === 'rejected' ? 'Отклонён' : 'На рассмотрении'}</span></div><h4>Идея решения</h4><p>{p.idea}</p><div className="proposal-columns"><div><h4>План работы</h4><p>{p.plan}</p></div><div><h4>Сроки</h4><p>{p.timeline}</p>{p.prototypeUrl && <a href={p.prototypeUrl} target="_blank" rel="noreferrer">Посмотреть прототип ↗</a>}</div></div>{p.feedback && <div className="notice"><b>Обратная связь бизнеса</b><p>{p.feedback}</p></div>}{identity.role === 'business' && <><label>Обратная связь команде<textarea disabled={busy} maxLength={2000} rows={2} value={feedback[p.id] ?? p.feedback ?? ''} onChange={e => setFeedback(current => ({ ...current, [p.id]: e.target.value }))} placeholder="Что понравилось? Что стоит уточнить?" /></label><div className="actions">{(['selected', 'rejected'] as const).map(status => <button key={status} className={status === 'selected' ? 'primary' : 'secondary'} disabled={busy} onClick={() => perform(async () => { await api(`/api/proposals/${p.id}`, 'PATCH', { status, feedback: feedback[p.id] ?? p.feedback ?? '' }); await reload(); setMessage('Решение и обратная связь сохранены.'); })}>{status === 'selected' ? 'Выбрать команду' : 'Отклонить'}</button>)}{p.status === 'selected' && <button className="secondary" disabled={busy || p.milestoneConfirmed} onClick={() => perform(async () => { await api(`/api/proposals/${p.id}/milestone`, 'PATCH', {}); await reload(); setMessage('Результат подтверждён: команде начислено 10 баллов.'); })}>{p.milestoneConfirmed ? '✓ Результат подтверждён · +10' : 'Подтвердить результат · +10'}</button>}</div></>}{identity.role === 'team' && p.milestoneConfirmed && <span className="status">Результат подтверждён · +10 баллов</span>}</article>; })}{!state.proposals.length && <div className="panel empty">Пока нет откликов. {identity.role === 'business' ? 'Опубликуйте задачу и дождитесь предложений команд.' : 'Найдите задачу в каталоге и предложите решение.'}</div>}</div></>}
    </>}<footer><a className="brand" href="#" onClick={e => { e.preventDefault(); setTab('catalog'); setLoginRole(null); }}>sana.</a><span>Задачи, с которых начинается дело.</span><span>Создано на HackAlem · 2026</span></footer></main>
    {selected && <div className="modal-backdrop" onClick={e => { if (e.target === e.currentTarget) setSelected(null); }}><section className="modal" role="dialog" aria-modal="true" aria-label={selected.title}><button autoFocus className="close-modal" aria-label="Закрыть задачу" onClick={() => setSelected(null)}>×</button><span className="tag">{selected.industry} · {state.businesses.find(b => b.id === selected.businessId)?.name || 'Бизнес'}</span><h2>{selected.title}</h2><div className="detail-layout"><div>{fields.filter(f => f !== 'title').map(f => <div className="detail-field" key={f}><h4>{FIELD_LABELS[f]}</h4><p>{selected[f] || 'Пока не указано'}</p></div>)}</div><ScoreView values={selected} confirmed={selected.confirmed} assessment={selected.assessment} /></div>{identity?.role === 'business' && identity.profileId === selected.businessId ? <button className="primary" onClick={() => editTask(selected)}>Редактировать задачу →</button> : identity?.role === 'team' && selected.published ? <form className="proposal-form" onSubmit={e => { e.preventDefault(); void sendProposal(); }}><h3>Решение от команды «{identity.name}»</h3><p className="muted">Отклик доступен при любом рейтинге задачи.</p>{(['idea', 'plan', 'timeline'] as const).map((f, i) => <label key={f}>{['Идея решения', 'План работы', 'Сроки'][i]}<textarea disabled={busy} required minLength={1} maxLength={f === 'timeline' ? 500 : 5000} rows={3} value={proposal[f]} onChange={e => setProposal(current => ({ ...current, [f]: e.target.value }))} /></label>)}<label>Ссылка на прототип · необязательно<input disabled={busy} type="url" maxLength={2048} placeholder="https://example.com/prototype" value={proposal.prototypeUrl} onChange={e => setProposal(current => ({ ...current, prototypeUrl: e.target.value }))} /></label><button className="primary" disabled={busy}>{busy ? 'Отправляем…' : 'Отправить отклик ↗'}</button>{error && <p role="alert" className="error-inline">{error}</p>}</form> : !identity && <button className="primary" onClick={() => openLogin('team')}>Войти как команда и откликнуться →</button>}</section></div>}
  </div>;
}
